name: Generate Snake (Dark Theme)

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate dark snake contribution grid
        uses: Platane/snk@v3
        with:
          github_user_name: SitharaGJ
          outputs: dist/github-contribution-grid-snake-dark.svg
          palette: "#0d1117 #161b22 #238636 #3fb950 #56d364"  # dark bg + green tones

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
